'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization
<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.telekom.net/csdg_v01.02", ClrNamespace:="schemas.telekom.net.csdg_v01._02")>

Namespace CourierServiceWriteService

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),
 System.ServiceModel.ServiceContractAttribute(Name:="ICourierServiceWriteService", [Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
    "iceWrite/v01")>
    Public Interface ICourierServiceWriteService

        <System.ServiceModel.OperationContractAttribute(Action:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/courierDeliveryStatus", ReplyAction:="*"),
     System.ServiceModel.FaultContractAttribute(GetType(schemas.telekom.net.csdg_v01._02.TCTechnicalFaultInfo), Action:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/courierDeliveryStatus", Name:="technicalFault", [Namespace]:="http://schemas.telekom.net/csdg_v01.02"),
     System.ServiceModel.XmlSerializerFormatAttribute()>
        Function courierDeliveryStatus(ByVal request As courierDeliveryStatusRequest) As courierDeliveryStatusResponse

        ''CODEGEN: Probíhá generování kontraktu zprávy, protože operace má více návratových hodnot.
        '<System.ServiceModel.OperationContractAttribute(Action:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        '"iceWrite/v01/courierDeliveryStatus", ReplyAction:="*")>
        'Function courierDeliveryStatusAsync(ByVal request As courierDeliveryStatusRequest) As System.Threading.Tasks.Task(Of courierDeliveryStatusResponse)
    End Interface

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.telekom.net/csdg_v01.02")>
    Partial Public Class TCContext

        Private technicalContextField As TCTechnicalContext

        Private businessContextField As TCBusinessContext

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property technicalContext() As TCTechnicalContext
            Get
                Return Me.technicalContextField
            End Get
            Set
                Me.technicalContextField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>
        Public Property businessContext() As TCBusinessContext
            Get
                Return Me.businessContextField
            End Get
            Set
                Me.businessContextField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.telekom.net/csdg_v01.02")>
    Partial Public Class TCTechnicalContext

        Private fromField As String

        Private routingInfoField As String

        Private messageIdField As String

        Private relatesToMessageIdField As String

        Private currentSenderTimestampUTCField As Date

        Private expiryOffsetInMillisField As String

        Private priorityField As Short

        Private priorityFieldSpecified As Boolean

        Private replyStateField As String

        Private propertyField() As TCProperty

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property from() As String
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>
        Public Property routingInfo() As String
            Get
                Return Me.routingInfoField
            End Get
            Set
                Me.routingInfoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>
        Public Property messageId() As String
            Get
                Return Me.messageIdField
            End Get
            Set
                Me.messageIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>
        Public Property relatesToMessageId() As String
            Get
                Return Me.relatesToMessageIdField
            End Get
            Set
                Me.relatesToMessageIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>
        Public Property currentSenderTimestampUTC() As Date
            Get
                Return Me.currentSenderTimestampUTCField
            End Get
            Set
                Me.currentSenderTimestampUTCField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=5)>
        Public Property expiryOffsetInMillis() As String
            Get
                Return Me.expiryOffsetInMillisField
            End Get
            Set
                Me.expiryOffsetInMillisField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>
        Public Property priority() As Short
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property prioritySpecified() As Boolean
            Get
                Return Me.priorityFieldSpecified
            End Get
            Set
                Me.priorityFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>
        Public Property replyState() As String
            Get
                Return Me.replyStateField
            End Get
            Set
                Me.replyStateField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("property", Order:=8)>
        Public Property [property]() As TCProperty()
            Get
                Return Me.propertyField
            End Get
            Set
                Me.propertyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.telekom.net/csdg_v01.02")>
    Partial Public Class TCProperty

        Private nameField As String

        Private typeField As TCPropertyType

        Private typeFieldSpecified As Boolean

        Private policyField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property type() As TCPropertyType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property typeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property policy() As String
            Get
                Return Me.policyField
            End Get
            Set
                Me.policyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.telekom.net/csdg_v01.02")>
    Public Enum TCPropertyType

        '''<remarks/>
        [string]

        '''<remarks/>
        int

        '''<remarks/>
        [boolean]

        '''<remarks/>
        float

        '''<remarks/>
        [date]
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.logica.com/eurotel-crm")>
    Partial Public Class ConfirmationMessage

        Private messageIDField As String

        Private requestIDField As String

        Private statusField As String

        Private caseIDField As String

        Private receivedAtField As Date

        Private receivedAtFieldSpecified As Boolean

        Private processedAtField As Date

        Private processedAtFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property messageID() As String
            Get
                Return Me.messageIDField
            End Get
            Set
                Me.messageIDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>
        Public Property requestID() As String
            Get
                Return Me.requestIDField
            End Get
            Set
                Me.requestIDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>
        Public Property caseID() As String
            Get
                Return Me.caseIDField
            End Get
            Set
                Me.caseIDField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>
        Public Property receivedAt() As Date
            Get
                Return Me.receivedAtField
            End Get
            Set
                Me.receivedAtField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property receivedAtSpecified() As Boolean
            Get
                Return Me.receivedAtFieldSpecified
            End Get
            Set
                Me.receivedAtFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>
        Public Property processedAt() As Date
            Get
                Return Me.processedAtField
            End Get
            Set
                Me.processedAtField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property processedAtSpecified() As Boolean
            Get
                Return Me.processedAtFieldSpecified
            End Get
            Set
                Me.processedAtFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
    "iceWrite/v01/types")>
    Partial Public Class CourierDeliveryStatusResponseType

        Private statusField As ConfirmationMessage

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property status() As ConfirmationMessage
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
    "iceWrite/v01/types")>
    Partial Public Class CourierDeliveryStatusResponseOutputType

        Private courierDeliveryStatusResponseTypeField As CourierDeliveryStatusResponseType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property courierDeliveryStatusResponseType() As CourierDeliveryStatusResponseType
            Get
                Return Me.courierDeliveryStatusResponseTypeField
            End Get
            Set
                Me.courierDeliveryStatusResponseTypeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
    "iceWrite/v01/types")>
    Partial Public Class CourierDeliveryStatusInputType

        Private shipmentIdField As String

        Private trackingIdField As String

        Private deliveryStatusField As String

        Private eventDateTimeField As Date

        Private deliveryStatusInfoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property shipmentId() As String
            Get
                Return Me.shipmentIdField
            End Get
            Set
                Me.shipmentIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>
        Public Property trackingId() As String
            Get
                Return Me.trackingIdField
            End Get
            Set
                Me.trackingIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>
        Public Property deliveryStatus() As String
            Get
                Return Me.deliveryStatusField
            End Get
            Set
                Me.deliveryStatusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>
        Public Property eventDateTime() As Date
            Get
                Return Me.eventDateTimeField
            End Get
            Set
                Me.eventDateTimeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>
        Public Property deliveryStatusInfo() As String
            Get
                Return Me.deliveryStatusInfoField
            End Get
            Set
                Me.deliveryStatusInfoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.telekom.net/csdg_v01.02")>
    Partial Public Class TCBusinessContext

        Private processIdField As String

        Private processTypeIdField As String

        Private messageGroupIdField As String

        Private processStepTypeIdField As String

        Private parentProcessIdField As String

        Private propertyField() As TCProperty

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>
        Public Property processId() As String
            Get
                Return Me.processIdField
            End Get
            Set
                Me.processIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>
        Public Property processTypeId() As String
            Get
                Return Me.processTypeIdField
            End Get
            Set
                Me.processTypeIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>
        Public Property messageGroupId() As String
            Get
                Return Me.messageGroupIdField
            End Get
            Set
                Me.messageGroupIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>
        Public Property processStepTypeId() As String
            Get
                Return Me.processStepTypeIdField
            End Get
            Set
                Me.processStepTypeIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>
        Public Property parentProcessId() As String
            Get
                Return Me.parentProcessIdField
            End Get
            Set
                Me.parentProcessIdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("property", Order:=5)>
        Public Property [property]() As TCProperty()
            Get
                Return Me.propertyField
            End Get
            Set
                Me.propertyField = Value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(),
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),
 System.ServiceModel.MessageContractAttribute(WrapperName:="courierDeliveryStatus", WrapperNamespace:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
    "iceWrite/v01", IsWrapped:=True)>
    Partial Public Class courierDeliveryStatusRequest

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types", Order:=0),
     System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types")>
        Public context As TCContext

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types", Order:=1),
     System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types")>
        Public dataIn As CourierDeliveryStatusInputType

        Public Sub New()
            MyBase.New
        End Sub

        Public Sub New(ByVal context As TCContext, ByVal dataIn As CourierDeliveryStatusInputType)
            MyBase.New
            Me.context = context
            Me.dataIn = dataIn
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(),
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),
 System.ServiceModel.MessageContractAttribute(WrapperName:="courierDeliveryStatusResponse", WrapperNamespace:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
    "iceWrite/v01", IsWrapped:=True)>
    Partial Public Class courierDeliveryStatusResponse

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types", Order:=0),
     System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types")>
        Public context As TCContext

        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types", Order:=1),
     System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.tsvk.telekom.net/SupAndPartMgmt/LogOrderMgmt/Couriers/CourierServ" &
        "iceWrite/v01/types")>
        Public data As CourierDeliveryStatusResponseOutputType

        Public Sub New()
            MyBase.New
        End Sub

        Public Sub New(ByVal context As TCContext, ByVal data As CourierDeliveryStatusResponseOutputType)
            MyBase.New
            Me.context = context
            Me.data = data
        End Sub
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
    Public Interface CourierServiceWriteChannel
        Inherits ICourierServiceWriteService, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(),
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
    Partial Public Class CourierServiceWriteClient
        Inherits System.ServiceModel.ClientBase(Of ICourierServiceWriteService)
        Implements ICourierServiceWriteService

        Public Sub New()
            MyBase.New
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
        Function CourierServiceWrite_courierDeliveryStatus(ByVal request As courierDeliveryStatusRequest) As courierDeliveryStatusResponse Implements ICourierServiceWriteService.courierDeliveryStatus
            Return MyBase.Channel.courierDeliveryStatus(request)
        End Function

        Public Function courierDeliveryStatus(ByRef context As TCContext, ByVal dataIn As CourierDeliveryStatusInputType) As CourierDeliveryStatusResponseOutputType
            Dim inValue As courierDeliveryStatusRequest = New courierDeliveryStatusRequest()
            inValue.context = context
            inValue.dataIn = dataIn
            Dim retVal As courierDeliveryStatusResponse = CType(Me, ICourierServiceWriteService).courierDeliveryStatus(inValue)
            context = retVal.context
            Return retVal.data
        End Function

        'Public Function courierDeliveryStatusAsync(ByVal request As courierDeliveryStatusRequest) As System.Threading.Tasks.Task(Of courierDeliveryStatusResponse) Implements ICourierServiceWriteServise.courierDeliveryStatusAsync
        '    Return MyBase.Channel.courierDeliveryStatusAsync(request)
        'End Function
    End Class
End Namespace

'Namespace schemas.telekom.net.csdg_v01._02

'    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
'     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
'     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
'     System.Xml.Serialization.XmlRootAttribute(ElementName:="technicalFault", [Namespace]:="http://schemas.telekom.net/csdg_v01.02", IsNullable:=false)>  _
'    Partial Public Class TCTechnicalFaultInfo
'        Inherits Object
'        Implements System.Xml.Serialization.IXmlSerializable

'        Private nodesField() As System.Xml.XmlNode

'        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("TCTechnicalFaultInfo", "http://schemas.telekom.net/csdg_v01.02")

'        Public Property Nodes() As System.Xml.XmlNode()
'            Get
'                Return Me.nodesField
'            End Get
'            Set
'                Me.nodesField = value
'            End Set
'        End Property

'        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
'            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
'        End Sub

'        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
'            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
'        End Sub

'        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
'            Return Nothing
'        End Function

'        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
'            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
'            Return typeName
'        End Function
'    End Class

'    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
'     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
'     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
'     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
'    Partial Public Class TCFaultInfo
'        Inherits Object
'        Implements System.Xml.Serialization.IXmlSerializable

'        Private nodesField() As System.Xml.XmlNode

'        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("TCFaultInfo", "http://schemas.telekom.net/csdg_v01.02")

'        Public Property Nodes() As System.Xml.XmlNode()
'            Get
'                Return Me.nodesField
'            End Get
'            Set
'                Me.nodesField = value
'            End Set
'        End Property

'        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
'            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
'        End Sub

'        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
'            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
'        End Sub

'        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
'            Return Nothing
'        End Function

'        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
'            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
'            Return typeName
'        End Function
'    End Class

'    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
'     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
'     System.Runtime.Serialization.DataContractAttribute(Name:="TCContext", [Namespace]:="http://schemas.telekom.net/csdg_v01.02")>  _
'    Partial Public Class TCContext
'        Inherits Object
'        Implements System.Runtime.Serialization.IExtensibleDataObject

'        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

'        Private technicalContextField As schemas.telekom.net.csdg_v01._02.TCTechnicalContext

'        Private businessContextField As schemas.telekom.net.csdg_v01._02.TCBusinessContext

'        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
'            Get
'                Return Me.extensionDataField
'            End Get
'            Set
'                Me.extensionDataField = value
'            End Set
'        End Property

'        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
'        Public Property technicalContext() As schemas.telekom.net.csdg_v01._02.TCTechnicalContext
'            Get
'                Return Me.technicalContextField
'            End Get
'            Set
'                Me.technicalContextField = value
'            End Set
'        End Property

'        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
'        Public Property businessContext() As schemas.telekom.net.csdg_v01._02.TCBusinessContext
'            Get
'                Return Me.businessContextField
'            End Get
'            Set
'                Me.businessContextField = value
'            End Set
'        End Property
'    End Class

'    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
'     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
'     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
'     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
'    Partial Public Class TCTechnicalContext
'        Inherits Object
'        Implements System.Xml.Serialization.IXmlSerializable

'        Private nodesField() As System.Xml.XmlNode

'        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("TCTechnicalContext", "http://schemas.telekom.net/csdg_v01.02")

'        Public Property Nodes() As System.Xml.XmlNode()
'            Get
'                Return Me.nodesField
'            End Get
'            Set
'                Me.nodesField = value
'            End Set
'        End Property

'        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
'            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
'        End Sub

'        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
'            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
'        End Sub

'        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
'            Return Nothing
'        End Function

'        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
'            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
'            Return typeName
'        End Function
'    End Class

'    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
'     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
'     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
'     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
'    Partial Public Class TCBusinessContext
'        Inherits Object
'        Implements System.Xml.Serialization.IXmlSerializable

'        Private nodesField() As System.Xml.XmlNode

'        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("TCBusinessContext", "http://schemas.telekom.net/csdg_v01.02")

'        Public Property Nodes() As System.Xml.XmlNode()
'            Get
'                Return Me.nodesField
'            End Get
'            Set
'                Me.nodesField = value
'            End Set
'        End Property

'        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
'            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
'        End Sub

'        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
'            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
'        End Sub

'        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
'            Return Nothing
'        End Function

'        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
'            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
'            Return typeName
'        End Function
'    End Class
'End Namespace
