'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization
<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://messaging.ei.tmobile.net/datatypes", ClrNamespace:="messaging.ei.tmobile.net.datatypes")> 


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
    "sdeliverymanagement", ConfigurationName:="WMSDeliveryManagement")>  _
Public Interface WMSDeliveryManagement
    
    <System.ServiceModel.OperationContractAttribute(Action:="/webservices/WMSDeliveryManagement/notifyPackageStatus", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(messaging.ei.tmobile.net.datatypes.SOABPException2), Action:="/webservices/WMSDeliveryManagement/notifyPackageStatus", Name:="TechnicalExceptionElement"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function notifyPackageStatus(ByVal request As notifyPackageStatusRequest) As notifyPackageStatusResponse
    
    'CODEGEN: Probíhá generování kontraktu zprávy, protože operace má více návratových hodnot.
    <System.ServiceModel.OperationContractAttribute(Action:="/webservices/WMSDeliveryManagement/notifyPackageStatus", ReplyAction:="*")>  _
    Function notifyPackageStatusAsync(ByVal request As notifyPackageStatusRequest) As System.Threading.Tasks.Task(Of notifyPackageStatusResponse)
    
    <System.ServiceModel.OperationContractAttribute(Action:="/webservices/WMSDeliveryManagement/receiveCourierLabel", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(messaging.ei.tmobile.net.datatypes.SOABPException2), Action:="/webservices/WMSDeliveryManagement/receiveCourierLabel", Name:="TechnicalExceptionElement"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function receiveCourierLabel(ByVal request As receiveCourierLabelRequest) As receiveCourierLabelResponse
    
    'CODEGEN: Probíhá generování kontraktu zprávy, protože operace má více návratových hodnot.
    <System.ServiceModel.OperationContractAttribute(Action:="/webservices/WMSDeliveryManagement/receiveCourierLabel", ReplyAction:="*")>  _
    Function receiveCourierLabelAsync(ByVal request As receiveCourierLabelRequest) As System.Threading.Tasks.Task(Of receiveCourierLabelResponse)
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://messaging.ei.tmobile.net/datatypes")>  _
Partial Public Class EIMessageContext2
    
    Private targetField As String
    
    Private replyToField As String
    
    Private requestIdField As String
    
    Private timeLeftField As Long
    
    Private timeLeftFieldSpecified As Boolean
    
    Private priorityField As Short
    
    Private priorityFieldSpecified As Boolean
    
    Private redeliveredField As EIMessageRedelivered
    
    Private redeliveredFieldSpecified As Boolean
    
    Private revisionField As String
    
    Private senderField As String
    
    Private correlationIdField As String
    
    Private sequenceIdField As String
    
    Private propertiesField() As EIMessageProperty
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property target() As String
        Get
            Return Me.targetField
        End Get
        Set
            Me.targetField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
    Public Property replyTo() As String
        Get
            Return Me.replyToField
        End Get
        Set
            Me.replyToField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
    Public Property requestId() As String
        Get
            Return Me.requestIdField
        End Get
        Set
            Me.requestIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
    Public Property timeLeft() As Long
        Get
            Return Me.timeLeftField
        End Get
        Set
            Me.timeLeftField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property timeLeftSpecified() As Boolean
        Get
            Return Me.timeLeftFieldSpecified
        End Get
        Set
            Me.timeLeftFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
    Public Property priority() As Short
        Get
            Return Me.priorityField
        End Get
        Set
            Me.priorityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property prioritySpecified() As Boolean
        Get
            Return Me.priorityFieldSpecified
        End Get
        Set
            Me.priorityFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
    Public Property redelivered() As EIMessageRedelivered
        Get
            Return Me.redeliveredField
        End Get
        Set
            Me.redeliveredField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property redeliveredSpecified() As Boolean
        Get
            Return Me.redeliveredFieldSpecified
        End Get
        Set
            Me.redeliveredFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
    Public Property revision() As String
        Get
            Return Me.revisionField
        End Get
        Set
            Me.revisionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
    Public Property sender() As String
        Get
            Return Me.senderField
        End Get
        Set
            Me.senderField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
    Public Property correlationId() As String
        Get
            Return Me.correlationIdField
        End Get
        Set
            Me.correlationIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger", Order:=9)>  _
    Public Property sequenceId() As String
        Get
            Return Me.sequenceIdField
        End Get
        Set
            Me.sequenceIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Order:=10),  _
     System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable:=false)>  _
    Public Property properties() As EIMessageProperty()
        Get
            Return Me.propertiesField
        End Get
        Set
            Me.propertiesField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://messaging.ei.tmobile.net/datatypes")>  _
Public Enum EIMessageRedelivered
    
    '''<remarks/>
    CLIENT
    
    '''<remarks/>
    SOABP
    
    '''<remarks/>
    MANUAL
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://messaging.ei.tmobile.net/datatypes")>  _
Partial Public Class EIMessageProperty
    
    Private nameField As String
    
    Private policyField As String
    
    Private mustUnderstandField As Boolean
    
    Private typeField As EIMessagePropertyType
    
    Private typeFieldSpecified As Boolean
    
    Private valueField As String
    
    Public Sub New()
        MyBase.New
        Me.mustUnderstandField = false
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified)>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified)>  _
    Public Property policy() As String
        Get
            Return Me.policyField
        End Get
        Set
            Me.policyField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public Property mustUnderstand() As Boolean
        Get
            Return Me.mustUnderstandField
        End Get
        Set
            Me.mustUnderstandField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified)>  _
    Public Property type() As EIMessagePropertyType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property typeSpecified() As Boolean
        Get
            Return Me.typeFieldSpecified
        End Get
        Set
            Me.typeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://messaging.ei.tmobile.net/datatypes")>  _
Public Enum EIMessagePropertyType
    
    '''<remarks/>
    [boolean]
    
    '''<remarks/>
    [byte]
    
    '''<remarks/>
    [short]
    
    '''<remarks/>
    int
    
    '''<remarks/>
    [long]
    
    '''<remarks/>
    float
    
    '''<remarks/>
    [double]
    
    '''<remarks/>
    [string]
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/datatypes/w"& _ 
    "msdeliverymanagement")>  _
Partial Public Class WMSDeliveryManagement_receiveCourierLabelResponse
    
    Private someDataField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property someData() As String
        Get
            Return Me.someDataField
        End Get
        Set
            Me.someDataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/datatypes/w"& _ 
    "msdeliverymanagement")>  _
Partial Public Class WMSDeliveryManagement_receiveCourierLabelRequest
    
    Private someDataField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property someData() As String
        Get
            Return Me.someDataField
        End Get
        Set
            Me.someDataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/datatypes/w"& _ 
    "msdeliverymanagement")>  _
Partial Public Class WMSDeliveryManagement_notifyPackageStatusResponse
    
    Private someDataField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property someData() As String
        Get
            Return Me.someDataField
        End Get
        Set
            Me.someDataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.2556.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/datatypes/w"& _ 
    "msdeliverymanagement")>  _
Partial Public Class WMSDeliveryManagement_notifyPackageStatusRequest
    
    Private someDataField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property someData() As String
        Get
            Return Me.someDataField
        End Get
        Set
            Me.someDataField = value
        End Set
    End Property
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="notifyPackageStatus", WrapperNamespace:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
    "sdeliverymanagement", IsWrapped:=true)>  _
Partial Public Class notifyPackageStatusRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=0)>  _
    Public eiMessageContext As EIMessageContext2
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=1)>  _
    Public data As WMSDeliveryManagement_notifyPackageStatusRequest
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal eiMessageContext As EIMessageContext2, ByVal data As WMSDeliveryManagement_notifyPackageStatusRequest)
        MyBase.New
        Me.eiMessageContext = eiMessageContext
        Me.data = data
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="notifyPackageStatusOutput", WrapperNamespace:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
    "sdeliverymanagement", IsWrapped:=true)>  _
Partial Public Class notifyPackageStatusResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=0)>  _
    Public eiMessageContext As EIMessageContext2
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=1)>  _
    Public data As WMSDeliveryManagement_notifyPackageStatusResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal eiMessageContext As EIMessageContext2, ByVal data As WMSDeliveryManagement_notifyPackageStatusResponse)
        MyBase.New
        Me.eiMessageContext = eiMessageContext
        Me.data = data
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="receiveCourierLabel", WrapperNamespace:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
    "sdeliverymanagement", IsWrapped:=true)>  _
Partial Public Class receiveCourierLabelRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=0)>  _
    Public eiMessageContext As EIMessageContext2
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=1)>  _
    Public data As WMSDeliveryManagement_receiveCourierLabelRequest
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal eiMessageContext As EIMessageContext2, ByVal data As WMSDeliveryManagement_receiveCourierLabelRequest)
        MyBase.New
        Me.eiMessageContext = eiMessageContext
        Me.data = data
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="receiveCourierLabelOutput", WrapperNamespace:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
    "sdeliverymanagement", IsWrapped:=true)>  _
Partial Public Class receiveCourierLabelResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=0)>  _
    Public eiMessageContext As EIMessageContext2
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", Order:=1)>  _
    Public data As WMSDeliveryManagement_receiveCourierLabelResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal eiMessageContext As EIMessageContext2, ByVal data As WMSDeliveryManagement_receiveCourierLabelResponse)
        MyBase.New
        Me.eiMessageContext = eiMessageContext
        Me.data = data
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface WMSDeliveryManagementChannel
    Inherits WMSDeliveryManagement, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class WMSDeliveryManagementClient
    Inherits System.ServiceModel.ClientBase(Of WMSDeliveryManagement)
    Implements WMSDeliveryManagement
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function WMSDeliveryManagement_notifyPackageStatus(ByVal request As notifyPackageStatusRequest) As notifyPackageStatusResponse Implements WMSDeliveryManagement.notifyPackageStatus
        Return MyBase.Channel.notifyPackageStatus(request)
    End Function
    
    Public Function notifyPackageStatus(ByRef eiMessageContext As EIMessageContext2, ByVal data As WMSDeliveryManagement_notifyPackageStatusRequest) As WMSDeliveryManagement_notifyPackageStatusResponse
        Dim inValue As notifyPackageStatusRequest = New notifyPackageStatusRequest()
        inValue.eiMessageContext = eiMessageContext
        inValue.data = data
        Dim retVal As notifyPackageStatusResponse = CType(Me,WMSDeliveryManagement).notifyPackageStatus(inValue)
        eiMessageContext = retVal.eiMessageContext
        Return retVal.data
    End Function
    
    Public Function notifyPackageStatusAsync(ByVal request As notifyPackageStatusRequest) As System.Threading.Tasks.Task(Of notifyPackageStatusResponse) Implements WMSDeliveryManagement.notifyPackageStatusAsync
        Return MyBase.Channel.notifyPackageStatusAsync(request)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function WMSDeliveryManagement_receiveCourierLabel(ByVal request As receiveCourierLabelRequest) As receiveCourierLabelResponse Implements WMSDeliveryManagement.receiveCourierLabel
        Return MyBase.Channel.receiveCourierLabel(request)
    End Function
    
    Public Function receiveCourierLabel(ByRef eiMessageContext As EIMessageContext2, ByVal data As WMSDeliveryManagement_receiveCourierLabelRequest) As WMSDeliveryManagement_receiveCourierLabelResponse
        Dim inValue As receiveCourierLabelRequest = New receiveCourierLabelRequest()
        inValue.eiMessageContext = eiMessageContext
        inValue.data = data
        Dim retVal As receiveCourierLabelResponse = CType(Me,WMSDeliveryManagement).receiveCourierLabel(inValue)
        eiMessageContext = retVal.eiMessageContext
        Return retVal.data
    End Function
    
    Public Function receiveCourierLabelAsync(ByVal request As receiveCourierLabelRequest) As System.Threading.Tasks.Task(Of receiveCourierLabelResponse) Implements WMSDeliveryManagement.receiveCourierLabelAsync
        Return MyBase.Channel.receiveCourierLabelAsync(request)
    End Function
End Class

Namespace messaging.ei.tmobile.net.datatypes
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
     System.Xml.Serialization.XmlRootAttribute(ElementName:="TechnicalExceptionElement", [Namespace]:="http://logisticsordermanagement.supplypartnermanagement.tmobile.cz/ws/services/wm"& _ 
        "sdeliverymanagement", IsNullable:=false)>  _
    Partial Public Class SOABPException2
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesField() As System.Xml.XmlNode
        
        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("SOABPException2", "http://messaging.ei.tmobile.net/datatypes")
        
        Public Property Nodes() As System.Xml.XmlNode()
            Get
                Return Me.nodesField
            End Get
            Set
                Me.nodesField = value
            End Set
        End Property
        
        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
        End Sub
        
        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
        End Sub
        
        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Return Nothing
        End Function
        
        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
            Return typeName
        End Function
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EIMessageContext2", [Namespace]:="http://messaging.ei.tmobile.net/datatypes")>  _
    Partial Public Class EIMessageContext2
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private targetField As String
        
        Private replyToField As String
        
        Private requestIdField As String
        
        Private timeLeftField As Long
        
        Private priorityField As Short
        
        Private redeliveredField As messaging.ei.tmobile.net.datatypes.EIMessageRedelivered
        
        Private revisionField As String
        
        Private senderField As String
        
        Private correlationIdField As String
        
        Private sequenceIdField As Long
        
        Private propertiesField As messaging.ei.tmobile.net.datatypes.EIMessagePropertyCollection
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property target() As String
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property replyTo() As String
            Get
                Return Me.replyToField
            End Get
            Set
                Me.replyToField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property requestId() As String
            Get
                Return Me.requestIdField
            End Get
            Set
                Me.requestIdField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property timeLeft() As Long
            Get
                Return Me.timeLeftField
            End Get
            Set
                Me.timeLeftField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property priority() As Short
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property redelivered() As messaging.ei.tmobile.net.datatypes.EIMessageRedelivered
            Get
                Return Me.redeliveredField
            End Get
            Set
                Me.redeliveredField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property revision() As String
            Get
                Return Me.revisionField
            End Get
            Set
                Me.revisionField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=7)>  _
        Public Property sender() As String
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=8)>  _
        Public Property correlationId() As String
            Get
                Return Me.correlationIdField
            End Get
            Set
                Me.correlationIdField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public Property sequenceId() As Long
            Get
                Return Me.sequenceIdField
            End Get
            Set
                Me.sequenceIdField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property properties() As messaging.ei.tmobile.net.datatypes.EIMessagePropertyCollection
            Get
                Return Me.propertiesField
            End Get
            Set
                Me.propertiesField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EIMessageRedelivered", [Namespace]:="http://messaging.ei.tmobile.net/datatypes")>  _
    Public Enum EIMessageRedelivered As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CLIENT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SOABP = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MANUAL = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="EIMessagePropertyCollection", [Namespace]:="http://messaging.ei.tmobile.net/datatypes", ItemName:="property")>  _
    Public Class EIMessagePropertyCollection
        Inherits System.Collections.Generic.List(Of messaging.ei.tmobile.net.datatypes.EIMessageProperty)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
    Partial Public Class EIMessageProperty
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesField() As System.Xml.XmlNode
        
        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("EIMessageProperty", "http://messaging.ei.tmobile.net/datatypes")
        
        Public Property Nodes() As System.Xml.XmlNode()
            Get
                Return Me.nodesField
            End Get
            Set
                Me.nodesField = value
            End Set
        End Property
        
        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
        End Sub
        
        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
        End Sub
        
        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Return Nothing
        End Function
        
        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
            Return typeName
        End Function
    End Class
End Namespace
